const discipline = [
  {
    discipline: {
      id: 1,
      name: "PHP",
      long_name: "Web Development",
      discipline_manager_id: 25,
      moodle_quiz_id: null,
      moodle_quiz_name: null,
      competence_group_id: null,
      creation_date: "2015-09-03T19:56:12.000Z",
      last_modified: "2020-11-12T12:31:34.000Z",
      deleted: 0,
      curricula_template_id: 858,
    },
    template: {
      id: 858,
      old_version: null,
      name: "Curriculum - PHP Web - Acreditat - 100 ore",
      child_template_id: null,
      is_document: 0,
      template_style_id: null,
      attachment_id: null,
      attachment_name: null,
      attachment_history: null,
      document_options:
        '{"rootStyle":{"height":"440px","min-height":"100%","width":"803px"},"paperSize":{"id":5,"name":"A4","height":1188,"width":803},"orientation":{"id":0,"name":"Portrait"},"usePageNumbers":null}',
      template_type_id: 3,
    },
  },
  {
    discipline: {
      id: 2,
      name: "QA",
      long_name: "Software Quality Assurance",
      discipline_manager_id: 34,
      moodle_quiz_id: null,
      moodle_quiz_name: null,
      competence_group_id: 2,
      creation_date: "2015-09-03T19:56:14.000Z",
      last_modified: "2022-11-09T21:49:54.000Z",
      deleted: 0,
      curricula_template_id: 929,
    },
    template: {
      id: 929,
      old_version: 684,
      name: "Curriculum - QA - Acreditat - 80 ore",
      child_template_id: null,
      is_document: 0,
      template_style_id: null,
      attachment_id: null,
      attachment_name: null,
      attachment_history: null,
      document_options:
        '{"rootStyle":{"height":"100%","min-height":"100%","width":"803px"},"paperSize":{"id":5,"name":"A4","height":1188,"width":803},"orientation":{"id":0,"name":"Portrait"},"usePageNumbers":null}',
      template_type_id: 3,
    },
  },
  {
    discipline: {
      id: 3,
      name: "Android",
      long_name: null,
      discipline_manager_id: 11,
      moodle_quiz_id: null,
      moodle_quiz_name: null,
      competence_group_id: null,
      creation_date: "2015-09-03T19:56:19.000Z",
      last_modified: "2016-05-13T11:27:24.000Z",
      deleted: 0,
      curricula_template_id: null,
      curricula: null,
    },
    template: {
      id: null,
      old_version: null,
      name: null,
      template_body: null,
      creation_date: null,
      child_template_id: null,
      is_document: null,
      template_style_id: null,
      attachment_id: null,
      attachment_name: null,
      attachment_history: null,
      document_options: null,
      template_type_id: null,
    },
  },
];
for (let x = 0; x < discipline.length; x++) {
  console.log(discipline[x].discipline.name);
}
